# Generated by Django 3.2.9 on 2022-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('full_text_1', models.TextField(null=True, verbose_name='статья-1')),
                ('full_text_2', models.TextField(null=True, verbose_name='статья-2')),
                ('full_text_3', models.TextField(null=True, verbose_name='статья-3')),
                ('full_text_4', models.TextField(null=True, verbose_name='статья-4')),
                ('full_text_5', models.TextField(null=True, verbose_name='статья-5')),
                ('full_text_6', models.TextField(null=True, verbose_name='статья-6')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='media/img/')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
